// Unexpire passwords for dev mode
zn "%SYS"
Do ##class(Security.Users).UnExpireUserPasswords("*")

// create IRISAPP namespace
do $SYSTEM.OBJ.Load("/opt/irisbuild/Installer.cls", "ck") 
set sc = ##class(App.Installer).setup() 

zn "HSLIB"

Do ##class(HS.HC.Util.Installer).InstallFoundation("IRISAPP")

zn "IRISAPP"
Do ##class(HS.FHIRServer.Installer).InstallNamespace()

;do $System.OBJ.LoadDir("/opt/irisbuild/src","ck",,1)
zpm "load /opt/irisbuild/ -v":1:1
halt
